refactor: template
dynamic-framework/dynamic-retail-loan-application-template pull request #1
Opened 2023-09-14 01:33 UTC by johannrp27

2023-09-15 18:23 UTC, abe-modyo commented on src/index.tsx
> +import '@dynamic-framework/ui-react/dist/css/dynamic-ui-all.css';
```suggestion
import '@dynamic-framework/ui-react/dist/css/dynamic-ui-react.css';
```

2023-09-15 18:24 UTC, abe-modyo requested changes
:D

2023-09-15 18:29 UTC, abe-modyo approved these changes, later dismissed

2023-09-21 22:48 UTC, efbarong commented on src/components/AdvancedSimulation.tsx
> +        <DCurrencyText value={monthlyPayment} className="display-5 fw-bold" />
`fs-5` no sería mejor aquí?

2023-09-21 22:48 UTC, efbarong commented on src/index.tsx
>  import '@dynamic-framework/ui-react/dist/css/dynamic-ui-react.css';
Creo que por ser template sería utilizar el `ui-all` para que al descargar de cero cargue con los estilos correctos

2023-09-21 22:48 UTC, efbarong commented on src/services/hooks/useApplyLoan.ts
> +  const userId = liquidParser.parse('{{user.id}}');
Usar variable global

2023-09-21 22:48 UTC, efbarong commented on src/services/hooks/useLoanRequestEffect.ts
> +  const userId = liquidParser.parse('{{user.id}}');
Usar variable global

2023-09-21 22:48 UTC, efbarong commented on src/services/ApiClient.ts
> +  baseURL: liquidParser.parse('{{vars.api-path}}'),
Usar variable global

2023-09-21 23:56 UTC, johannrp27 commented on src/index.tsx
>  import '@dynamic-framework/ui-react/dist/css/dynamic-ui-react.css';
Esto lo hablamos con Abe y tambien me parecería correcto el all. Pero si prueban a subirlo es mejor que vaya con react. Voy a revisar la vuelta del import dinamico

2023-09-22 00:42 UTC, johannrp27 commented on src/index.tsx
>  import '@dynamic-framework/ui-react/dist/css/dynamic-ui-react.css';
https://github.com/dynamic-framework/dynamic-ui/issues/450

2023-09-22 17:01 UTC, efbarong commented on src/index.tsx
>  import '@dynamic-framework/ui-react/dist/css/dynamic-ui-react.css';
Está bien, aunque esta task debería es ir asociada al template

2023-09-22 17:04 UTC, johannrp27 commented on src/index.tsx
>  import '@dynamic-framework/ui-react/dist/css/dynamic-ui-react.css';
#2

2023-09-22 17:08 UTC, efbarong commented on src/config/liquid.json
> +    "path-dashboard": "#",
Los `path` los hemos estado dejamos al final de la palabra, entonces sería `dashboard-path`

2023-09-22 17:08 UTC, efbarong commented on src/components/StatusRejected.tsx
>    const goToHome = () => {
Puede usar directamente el `goToPath` sin tener que crear una función adicional

2023-09-22 17:43 UTC, efbarong approved these changes

2023-09-22 17:45 UTC, merged