feat: live integration
dynamic-framework/dynamic-retail-loan-application-template pull request #21
Opened 2024-12-26 23:36 UTC by johannrp27

2025-01-03 13:34 UTC, lnazarit requested changes

2025-01-03 13:34 UTC, lnazarit commented on src/components/OffcanvasTermsAndConditions.tsx
>              Lorem ipsum dolor sit amet consectetur adipisicing elit.
Este texto en duro es así?

2025-01-03 17:12 UTC, johannrp27 commented on src/components/OffcanvasTermsAndConditions.tsx
>              Lorem ipsum dolor sit amet consectetur adipisicing elit.
Sip, no tenemos ningun formato de T&C entonces quedó el lorem

2025-01-07 13:15 UTC, lnazarit approved these changes, later dismissed

2025-01-07 18:08 UTC, efbarong commented on src/components/ApplicationForm.tsx
> +    );
```suggestion
    return <ApplicationStatus status={status} />;
```

2025-01-07 18:08 UTC, efbarong commented on src/components/StatusPending.tsx
> +  }, []);
En este caso como se está redireccionando a otra url sería mejor esto en un `<a href="xxx">`

2025-01-07 18:08 UTC, efbarong commented on src/components/StatusRejected.tsx
> +  }, []);
Lo mismo del `<a href="">`

2025-01-07 18:08 UTC, efbarong commented on src/services/hooks/useApplyLoan.ts
> +          userId: USER_ID,
Este valor esta llegando de una variable de liquid 🤔 
En el caso del demo funciona porque se tiene un usuario logueado
Pero en el catalogo, no

2025-01-07 18:08 UTC, efbarong commented on src/services/hooks/useSimulation.ts
> +          amount: amount ?? 0,
No debería dejar simular si es 0 🤔

2025-01-08 14:07 UTC, lnazarit requested changes

2025-01-08 14:07 UTC, lnazarit commented on src/services/api-interface.ts
> +  message_Code: string;
se pasó una mayuscula

2025-01-08 17:50 UTC, lnazarit approved these changes

2025-01-08 18:01 UTC, efbarong approved these changes

2025-01-08 18:38 UTC, merged